//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Erohin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.SostavOrder = new HashSet<SostavOrder>();
        }
    
        public int ID { get; set; }
        public string Status { get; set; }
        public string DateOfDelivery { get; set; }
        public Nullable<int> Postmat { get; set; }
        public string DateOfOrder { get; set; }
        public Nullable<int> User { get; set; }
        public Nullable<int> CodeOfPoluchenie { get; set; }
    
        public virtual Postmat Postmat1 { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SostavOrder> SostavOrder { get; set; }
    }
}
